spring:
  config:
    activate:
      on-profile: "security"

oauth:
  google:
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
      redirectUri: ${GOOGLE_REDIRECT_URI}

jwt:
  access-token-secret: ${JWT_ACCESS_TOKEN}
  refresh-token-secret: ${JWT_REFRESH_TOKEN}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  issuer: ${JWT_ISSUER}