name: Dev Deploy to AWS

on:
  push:
    branches: [ "cicd/#27" ]

env:
  DOCKERHUB_IMAGE_NAME: gigedi-server

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant Permissions for Gradle build
        run: chmod +x gradlew

      - name: Gradle building
        run: ./gradlew build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5.5.0
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKERHUB_IMAGE_NAME }}
          tags: |
            type=sha,prefix=

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}

      - name: Create .env file from GitHub Secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

  run-docker-image-on-ec2:
    needs: build-deploy
    runs-on: self-hosted

    steps:
      - name: Docker Pull
        run: sudo sudo docker pull ${{ secrets.DOCKER_USERNAME }}/shoot:latest

      - name: Stop and Remove Existing Container
        run: |
          sudo docker-compose down

      - name: Run New Docker Container
        run: |
          sudo docker-compose -d
